name = "glearray"
version = "2.0.0"

description = "Immutable arrays for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lunagl", repo = "glearray" }
links = []

[dependencies]
gleam_stdlib = { path = "../gleam-stdlib" }

# [dev-dependencies]
# gleeunit = "~> 1.1"
